### PR TITLE
Support math tags in slate

### PR DESCRIPTION
**Pull request by kodeebo**
Support deserialize and serialize of math tags. Need some polyfill to render correctly in editor

### CODE REVIEW

**Comment by oyvinmar** [comment]
Maybe add some tests?

**Comment by kodeebo** [comment]
ok @oyvinmar ?

**Comment by oyvinmar** [comment]
Very nice! 💯

**Comment by oyvinmar** [comment]
N.B! Don't merge this yet. We can't handle mathml as normal html, since slate will normalize mark tags (em, strong, etc) inside <math> tags which results in mathjax display errors.

**Pull request closed without merging**
